[package]
name = "window-observer"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
thiserror = "1.0.63"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58.0"
features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Accessibility"]

[target.'cfg(target_os = "windows")'.dependencies]
smallvec = "1.13.2"

[target.'cfg(target_os = "macos")'.dependencies]
accessibility-sys = "0.1.3"
core-foundation = "0.9.4"
objc2 = "0.5.2"
objc2-foundation = { version = "0.2.2", features = ["NSGeometry"] }
